### ISSUE TITLE
Fluxograma

### ISSUE THREAD

**Issue by CristianZatt** [CristianZatt/GCT#1]
https://drive.google.com/file/d/1XXlDyYmpEKeIc670Aavb47IdDDeqCt5y/view?usp=sharing

**Comment by CristianZatt** [comment]
https://drive.google.com/file/d/1XXlDyYmpEKeIc670Aavb47IdDDeqCt5y/view?usp=sharing

**Comment by YouFool** [comment]
Fechando a issue devido ao merge #11
